language: go
sudo: false
go:
- 1.13.x
matrix:
  fast_finish: true

before_install:
- make init dep

script:
- make verify

before_deploy:
- make release
- echo "Deploying to GitHub releases ..."

deploy:
  provider: releases
  api_key:
    secure: T9aBx7SHwIM1wz+Y5MqgAWqTuvhL1ll6xnEAA4AWPJdC4O1yGkbTjHqekd5rzM98qze276nNmAheCFGTj/9YR+GZko6dXcvBoOviBJX7kbPNOAAJleriYmywAWPGC18hYgsqPp14YSCdQevqneKtiBmLROpUEkte63MHD4fBMGtMY5svtbRKKvNmtzU2w1JNPMkhxYcJuWDT/ShnxOMPut4NhJ+XqujXOaHQCUIonuP8kFSDcXA9AyQNSLWpA/o+zxU63LTXuR8h6pVCb/Uw7/jiHfRl2CdM5GCnL5ChtgrnkzfAb3eO6LR/GdjLZwzGqh8kM2u4pH5EsGP/VrtikWkQt6JfBsX+GiaP3W6n4LmUz7a2SiIt4xn/1ahxqzdP21B9ouujKecH6qSelZ5jx/s7lF1FaDwrtwPapQKw4tT1GyX74IdooBnBvESgxNfCCg+bFgMZVdR/LtCTxVjsnSOilFJtenruAF0bKjvTJ4OCn4naV91Fl/9fpQIgqyyOdz68ZW2SSUeWaZcRVEG7jzXkXh1ynllDWNa5cm9p9v0Wb0eRipHCP5gR/TLjomeEcbadV4fMZShzg/dIt4DoRD/3sVol4KJxyl7ucbtPtG5NJRkspSWeBZQfvr8W+1xPYvzaP/4OSEkogPzY6JXkGvpScX+0uwDo0pmBykHq7Wc=
  skip_cleanup: true
  on:
    repo: VirtusLab/crypt
    tags: true
  file:
  - cross/crypt-darwin-amd64
  - cross/crypt-darwin-amd64.md5
  - cross/crypt-darwin-amd64.sha256
  - cross/crypt-darwin-386
  - cross/crypt-darwin-386.md5
  - cross/crypt-darwin-386.sha256
  - cross/crypt-freebsd-amd64
  - cross/crypt-freebsd-amd64.md5
  - cross/crypt-freebsd-amd64.sha256
  - cross/crypt-freebsd-386
  - cross/crypt-freebsd-386.md5
  - cross/crypt-freebsd-386.sha256
  - cross/crypt-linux-arm
  - cross/crypt-linux-arm.md5
  - cross/crypt-linux-arm.sha256
  - cross/crypt-linux-arm64
  - cross/crypt-linux-arm64.md5
  - cross/crypt-linux-arm64.sha256
  - cross/crypt-linux-amd64
  - cross/crypt-linux-amd64.md5
  - cross/crypt-linux-amd64.sha256
  - cross/crypt-linux-386
  - cross/crypt-linux-386.md5
  - cross/crypt-linux-386.sha256
  - cross/crypt-windows-amd64
  - cross/crypt-windows-amd64.md5
  - cross/crypt-windows-amd64.sha256
  - cross/crypt-windows-386
  - cross/crypt-windows-386.md5
  - cross/crypt-windows-386.sha256

cache:
  directories:
    - vendor
