name: Makefile CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - name: Install dependencies
      run: make init
      
    - name: Run build and check
      run: make status verify

